const ANALYSIS_STATUS = Object.freeze({
  UNDERVALUED: 'UNDERVALUED',
  FAIR_VALUE: 'FAIR_VALUE',
  OVERVALUED: 'OVERVALUED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  ERROR: 'ERROR',
});

module.exports = {
  ANALYSIS_STATUS,
};
